services:
  mongors1n1:
    image: mongo:latest
    container_name: mongors1n1
    ports:
      - 27017:${MONGO_PORT}
    expose:
      - ${MONGO_PORT}
    volumes:
      - ./mongo_cluster/data1:/data/db
    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port ${MONGO_PORT}

  mongors1n2:
    image: mongo:latest
    container_name: mongors1n2
    ports:
      - 27027:${MONGO_PORT}
    expose:
      - ${MONGO_PORT}
    volumes:
      - ./mongo_cluster/data2:/data/db
    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port ${MONGO_PORT}

  mongors1n3:
    image: mongo:latest
    container_name: mongors1n3
    ports:
      - 27037:${MONGO_PORT}
    expose:
      - ${MONGO_PORT}
    volumes:
      - ./mongo_cluster/data3:/data/db
    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port ${MONGO_PORT}

  mongors2n1:
    image: mongo:latest
    container_name: mongors2n1
    ports:
      - 27047:${MONGO_PORT}
    expose:
      - ${MONGO_PORT}
    volumes:
      - ./mongo_cluster/data4:/data/db
    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port ${MONGO_PORT}

  mongors2n2:
    image: mongo:latest
    container_name: mongors2n2
    ports:
      - 27057:${MONGO_PORT}
    expose:
      - ${MONGO_PORT}
    volumes:
      - ./mongo_cluster/data5:/data/db
    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port ${MONGO_PORT}

  mongors2n3:
    image: mongo:latest
    container_name: mongors2n3
    ports:
      - 27067:${MONGO_PORT}
    expose:
      - ${MONGO_PORT}
    volumes:
      - ./mongo_cluster/data6:/data/db
    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port ${MONGO_PORT}

  mongocfg1:
    image: mongo:latest
    container_name: mongocfg1
    expose:
      - ${MONGO_PORT}
    volumes:
      - ./mongo_cluster/config1:/data/db
    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port ${MONGO_PORT}

  mongocfg2:
    image: mongo:latest
    container_name: mongocfg2
    expose:
      - ${MONGO_PORT}
    volumes:
      - ./mongo_cluster/config2:/data/db
    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port ${MONGO_PORT}

  mongocfg3:
    image: mongo:latest
    container_name: mongocfg3
    expose:
      - ${MONGO_PORT}
    volumes:
      - ./mongo_cluster/config3:/data/db
    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port ${MONGO_PORT}

  mongos1:
    image: mongo:latest
    container_name: mongos1
    ports:
      - 27019:${MONGO_PORT}
    expose:
      - ${MONGO_PORT}
    depends_on:
      - mongocfg1
      - mongocfg2
      - mongocfg3
    command: >
      mongos 
      --configdb mongors1conf/mongocfg1:${MONGO_PORT},mongocfg2:${MONGO_PORT},mongocfg3:${MONGO_PORT}
      --port ${MONGO_PORT}
      --bind_ip_all

  mongos2:
    image: mongo:latest
    container_name: mongos2
    ports:
      - 27020:${MONGO_PORT}
    expose:
      - ${MONGO_PORT}
    depends_on:
      - mongocfg1
      - mongocfg2
      - mongocfg3
    command: >
      mongos 
      --configdb mongors1conf/mongocfg1:${MONGO_PORT},mongocfg2:${MONGO_PORT},mongocfg3:${MONGO_PORT}
      --port ${MONGO_PORT}
      --bind_ip_all

  mongo-cluster:
    image: mongo:latest
    container_name: mongo-cluster
    expose:
      - ${MONGO_PORT}
    env_file:
      - .env
    depends_on:
      - mongos1
      - mongos2
    volumes:
      - ./mongodb.sh:/docker-entrypoint-initdb.d/mongodb.sh
    entrypoint: sh -c /docker-entrypoint-initdb.d/mongodb.sh
    restart: on-failure

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ugc-service
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - mongo-cluster
    entrypoint: >
      sh -c "
      cd ugc_service &&
      uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
      "
    restart: on-failure

  nginx:
    image: nginx:latest
    container_name: nginx-server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - fastapi
