services:
  elasticsearch:
    image: elasticsearch:8.10.2
    container_name: elk-es
    ports:
      - 9200:9200
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: "false"

  logstash:
    image: logstash:8.10.2
    container_name: logstash
    ports:
      - 5044:5044/udp
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: "elasticsearch:9200"
    volumes:
      - ./logstash.conf:/config/logstash.conf:ro
    command: logstash -f /config/logstash.conf

  kibana:
    image: kibana:8.10.2
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    depends_on:
      - elasticsearch
